# Output 输出
resolution = [1280, 720]
fps = 60
ffmpegPreset = "medium p4 medium balanced" # "cpu nvenc qsv amf"
hardwareAccel = true
sampleCount = 2
hevc = false
mpeg4 = false
customEncoder = "libx264"
bitrateControl = "CRF"
bitrate = "26"


# Player 玩家
# playerAvatar = ""
playerName = "Dehou23333"
playerRks = 16.0
challengeColor = "rainbow"
challengeRank = 3


# Graphics 图像
# res_pack_path = ""
noteScale = 1.0
chartDebug = 1.0
chartRatio = 0.40

disableLoading = false
renderLine = true
renderLineExtra = true
renderNote = true
renderUiPause = true
renderUiName = true
renderUiLevel = true
renderUiScore = true
renderUiCombo = true
renderUiBar = true
renderBg = true
renderBgDim = true
particle = true
disableEffect = false
doubleHint = true

aggressive = false
roman = false
chinese = false

bgBlurriness = 80.0


# Audio 音频
forceLimit = true
hires = false
volumeMusic = 1.0
volumeSfx = 0.7
compressionRatio = 20.0
limitThreshold = 1.0


# Other 其他
endingLength = 10.0
watermark = "Rendered with Phi-Recorder."
combo = "AUTOPLAY"
difficulty = ""
allGood = false
allBad = false
judgeOffset = 0.0
maxParticles = 1000
fade = 0.0

simpleFileName = false
fxaa = false
speed = 1.0
