name: Install FFmpeg

on: [push]

jobs:
  Render:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Base Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            xvfb \
            libgl1-mesa-glx \
            libgl1-mesa-dri \
            mesa-utils \
            pulseaudio \
            alsa-utils \
            libva-drm2 \
            libva-x11-2 \
            libvdpau1 \
            libxcb1 \
            libxcb-shm0 \
            libxcb-xfixes0 \
            build-essential \
            cmake \
            libasound2-dev \
            libpulse-dev \
            libusb-1.0-0-dev \
            libdbus-1-dev \
            libudev-dev

      - name: Compile SDL2 2.0.20
        run: |
          wget https://github.com/libsdl-org/SDL/archive/refs/tags/release-2.0.20.tar.gz
          tar xvf release-2.0.20.tar.gz
          cd SDL-release-2.0.20
          mkdir build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=/usr
          make -j$(nproc)
          sudo make install
          sudo ldconfig

      - name: Install Static FFmpeg
        run: |
          wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
          tar xvf ffmpeg-release-amd64-static.tar.xz
          cd ffmpeg-*-amd64-static
          sudo mv ffmpeg ffprobe /usr/local/bin/
          sudo ldconfig

      - name: Install Phi-Recorder
        run: |
          LATEST_RELEASE=$(curl -s "https://api.github.com/repos/2278535805/Phi-Recorder/releases/latest" | jq -r '.tag_name')
          LATEST_VERSION="${LATEST_RELEASE:1}"
          DEB_URL="https://github.com/2278535805/Phi-Recorder/releases/download/v${LATEST_VERSION}/phi-recorder_${LATEST_VERSION}_amd64.deb"
          wget "${DEB_URL}" -O phi-recorder.deb
          sudo dpkg -i phi-recorder.deb || (sudo apt-get update && sudo apt-get install -f -y)

      - name: Render with Xvfb
        run: |
          # 配置音频环境
          mkdir -p ~/.config/pulse
          echo "default-server = unix:/tmp/pulse.socket" > ~/.config/pulse/client.conf
          pulseaudio --daemonize --exit-idle-time=-1 --log-level=4 --file=/tmp/pulse.log

          # 设置兼容性环境
          export LIBGL_ALWAYS_SOFTWARE=1
          export MESA_GL_VERSION_OVERRIDE=3.3
          export SDL_AUDIODRIVER=pulseaudio
          export PULSE_SERVER=unix:/tmp/pulse.socket

          # 验证组件
          sdl2-config --version
          ffmpeg -version | head -n1
          
          # 启动渲染
          xvfb-run -s "-screen 0 1920x1080x24 -ac" \
            timeout 600s phi-recorder \
            --render AbsoluTedisoRdeR.AcuteDisarray-AT.pez \
            --output "ATRR.mp4" \
            --ffmpeg-args "-filter_complex 'amix=inputs=3:duration=first:normalize=0'"
        env:
          RUST_BACKTRACE: full
