name: Install FFmpeg

on: [push]

jobs:
  Render:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Base Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            xvfb \
            pulseaudio \
            alsa-utils \
            dbus-x11

      - name: Configure PulseAudio
        run: |
          # 创建配置目录
          mkdir -p ~/.config/pulse/
          
          # 正确的daemon配置
          echo "default-sample-format = s16le
          default-sample-rate = 44100
          realtime-scheduling = yes
          exit-idle-time = -1
          daemonize = yes
          " > ~/.config/pulse/daemon.conf

          # 正确的client配置
          echo "autospawn = no
          default-server = unix:/tmp/pulse.socket
          " > ~/.config/pulse/client.conf

      - name: Start PulseAudio
        run: |
          # 启动命令需要显式指定配置文件路径
          pulseaudio \
            --daemonize \
            --log-target=file:/tmp/pulse.log \
            --log-level=debug \
            --disable-shm \
            --file=~/.config/pulse/daemon.conf \
            --high-priority

          # 验证服务状态
          sleep 2
          pactl --server=unix:/tmp/pulse.socket info

      - name: Render with Xvfb
        run: |
          export LIBGL_ALWAYS_SOFTWARE=1
          export SDL_AUDIODRIVER=pulseaudio
          export PULSE_SERVER=unix:/tmp/pulse.socket

          xvfb-run -s "-screen 0 1920x1080x24 -ac" \
            timeout 600s phi-recorder \
            --render your-file.pez \
            --output "output.mp4"
