name: Install FFmpeg

on: [push]

jobs:
  Render:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          # 使用支持Ubuntu 20.04的FFmpeg PPA
          sudo add-apt-repository ppa:savoury1/ffmpeg5 -y
          sudo apt-get install -y \
            ffmpeg \
            xvfb \
            libayatana-appindicator3-1 \
            libwebkit2gtk-4.0-37 \
            libgl1-mesa-glx \
            libgl1-mesa-dri \
            mesa-utils \
            pulseaudio \
            alsa-utils \
            libavcodec-dev \
            libavfilter-dev

      - name: Install Phi-Recorder
        run: |
          LATEST_RELEASE=$(curl -s "https://api.github.com/repos/2278535805/Phi-Recorder/releases/latest" | jq -r '.tag_name')
          LATEST_VERSION="${LATEST_RELEASE:1}"
          DEB_URL="https://github.com/2278535805/Phi-Recorder/releases/download/v${LATEST_VERSION}/phi-recorder_${LATEST_VERSION}_amd64.deb"
          wget "${DEB_URL}" -O phi-recorder.deb
          sudo dpkg -i phi-recorder.deb || (sudo apt-get update && sudo apt-get install -f -y)

      - name: Render with Xvfb
        run: |
          # 配置虚拟音频环境
          mkdir -p ~/.config/pulse
          echo "default-server = unix:/tmp/pulseaudio.socket" > ~/.config/pulse/client.conf
          pulseaudio --daemonize --exit-idle-time=-1 --log-level=4 --file=/tmp/pulseaudio.log

          # 设置OpenGL兼容模式
          export LIBGL_ALWAYS_SOFTWARE=1
          export MESA_GL_VERSION_OVERRIDE=3.3COMPAT

          # 验证FFmpeg过滤器
          ffmpeg -hide_banner -h filter=amix | grep -i normalize
          
          # 启动渲染进程
          xvfb-run -s "-screen 0 1920x1080x24 -ac" \
            timeout 600s phi-recorder \
            --render AbsoluTedisoRdeR.AcuteDisarray-AT.pez \
            --output "ATRR.mp4" \
            --ffmpeg-args "-filter_complex 'amix=inputs=3:duration=first:normalize=0,volume=2.0'"
        env:
          RUST_BACKTRACE: 1
          SDL_AUDIODRIVER: pulseaudio
          PULSE_SERVER: unix:/tmp/pulseaudio.socket
