name: Install FFmpeg

on: [push]

jobs:
  Render:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Base Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            xvfb \
            libgl1-mesa-glx \
            libgl1-mesa-dri \
            mesa-utils \
            pulseaudio \
            alsa-utils \
            libva-drm2 \
            libxcb1 \
            libxcb-shm0 \
            libxcb-xfixes0 \
            dbus-x11

      - name: Configure PulseAudio
        run: |
          # 清理旧配置
          rm -rf ~/.config/pulse || true
          
          # 创建虚拟音频设备
          mkdir -p ~/.config/pulse
          echo "default-sample-format = s16le
          default-sample-rate = 44100
          realtime-scheduling = yes
          exit-idle-time = -1
          daemonize = no
          default-server = unix:/tmp/pulse.socket
          " > ~/.config/pulse/daemon.conf

          # 创建客户端配置
          echo "autospawn = no
          default-server = unix:/tmp/pulse.socket
          " > ~/.config/pulse/client.conf

      - name: Start PulseAudio Server
        run: |
          # 启动独立的PulseAudio实例
          pulseaudio \
            --daemonize \
            --log-target=file:/tmp/pulse.log \
            --log-level=debug \
            --disable-shm \
            --exit-idle-time=-1 \
            --file=/tmp/pulse-config

      - name: Verify Audio System
        run: |
          sleep 2  # 等待服务启动
          pactl --server=unix:/tmp/pulse.socket list sinks
          grep -i error /tmp/pulse.log && exit 1 || true

      - name: Render with Xvfb
        run: |
          export LIBGL_ALWAYS_SOFTWARE=1
          export MESA_GL_VERSION_OVERRIDE=3.3
          export SDL_AUDIODRIVER=pulseaudio
          export PULSE_SERVER=unix:/tmp/pulse.socket

          # 创建虚拟音频设备
          pactl --server=unix:/tmp/pulse.socket load-module module-null-sink sink_name=VirtualSpeaker
          pactl --server=unix:/tmp/pulse.socket load-module module-null-source source_name=VirtualMic

          xvfb-run -s "-screen 0 1920x1080x24 -ac" \
            timeout 600s phi-recorder \
            --render AbsoluTedisoRdeR.AcuteDisarray-AT.pez \
            --output "ATRR.mp4"
        env:
          RUST_BACKTRACE: full
