name: Render Video

on: [push]

jobs:
  Render:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            xvfb \
            libgl1-mesa-glx \
            libasound2 \
            alsa-utils

      - name: Install Static FFmpeg
        run: |
          # 下载预编译版本
          wget https://github.com/eugeneware/ffmpeg-static/releases/download/b5.0.1/linux-x64
          chmod +x linux-x64
          sudo mv linux-x64 /usr/local/bin/ffmpeg
          sudo ln -s /usr/local/bin/ffmpeg /usr/local/bin/ffprobe

      - name: Configure ALSA Null Device
        run: |
          # 创建虚拟音频设备配置
          echo 'pcm.!default {
            type plug
            slave.pcm "null"
          }

          ctl.!default {
            type hw
            card 0
          }' | tee ~/.asoundrc

          # 验证ALSA配置
          aplay -l

      - name: Install Phi-Recorder
        run: |
          LATEST_RELEASE=$(curl -s "https://api.github.com/repos/2278535805/Phi-Recorder/releases/latest" | jq -r '.tag_name')
          LATEST_VERSION="${LATEST_RELEASE:1}"
          wget "https://github.com/2278535805/Phi-Recorder/releases/download/v${LATEST_VERSION}/phi-recorder_${LATEST_VERSION}_amd64.deb" -O phi-recorder.deb
          sudo dpkg -i phi-recorder.deb || sudo apt-get install -f -y

      - name: Run Render
        run: |
          export LIBGL_ALWAYS_SOFTWARE=1
          export SDL_AUDIODRIVER=alsa  # 强制使用ALSA
          export MESA_GL_VERSION_OVERRIDE=3.3

          # 静默运行音频测试
          timeout 5s arecord -d 5 test.wav >/dev/null 2>&1 || true

          xvfb-run -s "-screen 0 1920x1080x24" \
            phi-recorder \
            --render AbsoluTedisoRdeR.AcuteDisarray-AT.pez \
            --output "ATRR.mp4" \
            --no-audio  # 如果支持禁用音频选项
        env:
          RUST_BACKTRACE: 1
        
      - name: Upload Video Artifact
        uses: actions/upload-artifact@v3
        with:
          name: rendered-video
          path: ATRR.mp4
          retention-days: 3
