name: Render PEZ File (Windows)

on:
  push:
    branches:
      - main

jobs:
  render:
    runs-on: windows-latest  # 切换为Windows运行环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Audio System
        shell: powershell
        run: |
          # 安装虚拟音频驱动（参考网页6、7、8中FFmpeg的Windows配置思路）
          choco install virtual-audio-device -y --ignore-checksums
          
          # 配置音频路由（需预装VB-CABLE，此处为示例配置）
          Start-Process -FilePath "C:\Program Files\VB\CABLE\VBCABLE_Setup_x64.exe" -ArgumentList "-i -h"

      - name: Install FFmpeg
        run: |
          choco install ffmpeg -y  # 使用Chocolatey安装（参考网页6、7、8的安装方法）
          refreshenv

      - name: Install Phi-Recorder
        shell: powershell
        run: |
          # 下载最新Windows版安装包（参考网页9的安装包处理方式）
          $release = Invoke-RestMethod 'https://api.github.com/repos/2278535805/Phi-Recorder/releases/latest'
          $asset = $release.assets | Where-Object { $_.name -like '*windows*.exe' }
          Invoke-WebRequest $asset.browser_download_url -OutFile phi-recorder-setup.exe
          
          # 静默安装
          Start-Process -FilePath .\phi-recorder-setup.exe -ArgumentList "/S" -Wait

      - name: Prepare PEZ File
        shell: powershell
        run: |
          New-Item -ItemType Directory -Path .\pez_files -Force
          $pezFile = Get-ChildItem -Filter *.pez | Select-Object -First 1
          Copy-Item $pezFile.FullName "pez_files\$($pezFile.Name)"
          Write-Output "PEZ_BASENAME=$($pezFile.Name)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Debug Audio Config
        shell: powershell
        run: |
          # Windows音频设备验证（参考网页9的系统检测思路）
          Get-PnpDevice -Class "Media" | Format-Table
          ffmpeg -list_devices true -f dshow -i dummy

      - name: Render with Headless Display
        shell: powershell
        env:
          DISPLAY: ':0'
        run: |
          # 使用Windows自带的Headless模式（参考网页9的无界面运行思路）
          phi-recorder --render "pez_files\$env:PEZ_BASENAME" --output ATRR.mp4

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rendered-video
          path: ATRR.mp4
