name: Render PEZ File

on:
  push:
    branches:
      - main  # 或者你想要触发的任何分支

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check available libwebkit2gtk versions
        run: apt-cache search libwebkit2gtk

