name: Install FFmpeg

on: [push]

jobs:
  Render:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg xvfb libayatana-appindicator3-1 libwebkit2gtk-4.0-37

      - name: Install Phi-Recorder
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/2278535805/Phi-Recorder/releases/latest | jq -r '.tag_name')
          LATEST_VERSION="${LATEST_RELEASE:1}"
          DEB_URL="https://github.com/2278535805/Phi-Recorder/releases/download/v${LATEST_VERSION}/phi-recorder_${LATEST_VERSION}_amd64.deb"
          wget "${DEB_URL}" -O phi-recorder.deb
          sudo dpkg -i phi-recorder.deb

      - name: Render with Xvfb
        run: xvfb-run phi-recorder --render --output "ATRR.mp4"
