name: Download Phigros APK

on: [push]

jobs:
  download_apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Phigros Resource
        uses: actions/checkout@v4
        with:
          repository: 7aGiven/Phigros_Resource
          ref: master

      - name: Get APK URL
        id: get_url
        run: |
          python -c "import taptap; import os; url = taptap.taptap(165287); print(url); os.system('wget %s' % url); os.system('mv *.apk phigros.apk')"

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: phigros.apk
          path: phigros.apk
