name: Download Phigros APK

on:
  push:
    branches:
      - main
    paths:
      - illustration/**
      - chart/**
  workflow_dispatch: # 添加 workflow_dispatch 以支持手动触发

jobs:
  download_apk:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 授予写入仓库内容的权限

    steps:
      - name: Checkout Phigros Resource
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download
        id: download
        run: |
          python download.py
      - name: Unpack
        run: |
          python gameInformation.py phigros.apk
          python resource.py phigros.apk
      - name: Upload Phigros
        uses: actions/upload-artifact@v4
        with:
          name: Phigros
          path: Phigros.apk
          retention-days: 3
