name: Download Phigros APK

on: [push]

jobs:
  download_apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Phigros Resource
        uses: actions/checkout@v4
        with:
          repository: 7aGiven/Phigros_Resource
          ref: master

      - name: Get APK URL
        id: get_url
        run: |
          output=$(python taptap.py)
          second_line=$(echo "$output" | awk 'NR==2')
          apk_data=$(echo "$second_line" | python -c 'import json, sys; print(json.loads(sys.stdin)["data"]["apk"]["download"])')
          echo "apk_url=$apk_data" >> $GITHUB_OUTPUT

      - name: Download APK
        run: |
          wget "${{ steps.get_url.outputs.apk_url }}" -O phigros.apk

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: phigros.apk
          path: phigros.apk
