name: Download Phigros APK

on: [push]

jobs:
  download_apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Phigros Resource
        uses: actions/checkout@v4

      - name: Download
        id: download
        run: |
          python download.py

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: phigros.apk
          path: phigros.apk
