name: Download Phigros APK

on:
  push:
    branches:
      - main
    paths:
      - illustration/**
      - chart/**
  workflow_dispatch: # 添加 workflow_dispatch 以支持手动触发

jobs:
  download_apk:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 授予写入仓库内容的权限

    steps:
      - name: Checkout Phigros Resource
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download
        id: download
        run: |
          python download.py
      - name: Unpack
        run: |
          python gameInformation.py phigros.apk
          python resource.py phigros.apk
      - name: Commit Illustration Folder
        run: |
          git config --local user.name "Github Actions"
          git config --local user.email "githubactions@github.com"
          cd illustration
          git add .
          git commit -m "illustrations"
          git push --force origin HEAD:illustration
      - name: Commit Chart Folder
        run: |
          cd ../chart
          git add .
          git commit -m "charts"
          git push --force origin HEAD:chart
