name: Download Phigros APK

on: [push]

jobs:
  download_apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Phigros Resource
        uses: actions/checkout@v4
        with:
          repository: 7aGiven/Phigros_Resource
          ref: master

      - name: Get APK URL
        id: get_url
        run: |
          python taptap.py
          echo "apk_url=$(python taptap.py | jq -r '.data.apk.download')" >> $GITHUB_OUTPUT

      - name: Download APK
        run: |
          wget "${{ steps.get_url.outputs.apk_url }}" -O phigros.apk

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: phigros.apk
          path: phigros.apk
