name: Download Phigros APK

on: [push]

jobs:
  download_apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout Phigros Resource
        uses: actions/checkout@v4
        with:
          repository: 7aGiven/Phigros_Resource
          ref: master

      - name: Get APK URL
        id: get_url
        run: |
          cd ../
          ls -l
          pwd
          url = $(python download.py)
          echo "apk_url=$url" >> $GITHUB_OUTPUT

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: phigros.apk
          path: phigros.apk
